### ISSUE TITLE
Strange exception error given when invalid Thread_ID given

### ISSUE THREAD

**Issue by antonizoon** [bibanon/py420chan#1]
An odd exception occurs when an invalid thread_id or board is given. This is unhelpful to the developer, as it gives no indication that there are any issues with thread_ids. It can be avoided by simply providing a valid thread ID though.

On basc_py4chan, it simply gives an empty thread object. Maybe there should be exception handling?

**Comment by Amersel** [comment]
```
>>> import py420chan
>>> nom = py420chan.Board('nom')
>>> thread = nom.get_thread(12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amersel/Git/py420chan/py420chan/board.py", line 140, in get_thread
    thread = Thread._from_request(self, res, thread_id)
  File "/home/amersel/Git/py420chan/py420chan/thread.py", line 53, in _from_request
    return cls._from_json(res.json(), board, id)
  File "/home/amersel/Git/py420chan/py420chan/thread.py", line 62, in _from_json
    head, rest = posts[0], posts[1:]
IndexError: string index out of range
```

**Comment by antonizoon** [comment]
completed in this commit, returns None object on IndexError

https://github.com/bibanon/py420chan/commit/da67c81d3504e568b23f42a1dd3404d2d6eeb9b4
